development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: rmj_io
  pool: 5
  port: 5432
  timeout: 5000
  username: dev
  password: test

# use when a migration is needed
# development:
#   adapter: postgresql
#   host: <%= ENV["DB_HOST"] %>
#   encoding: unicode
#   database: <%= ENV["DB_NAME"] %>
#   pool: 5
#   port: 5432
#   timeout: 5000
#   username: <%= ENV["DB_USER"] %>
#   password: <%= ENV["DB_PASS"] %>